// Deno Edge Function to send troubleshooting emails via SendGrid
import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Methods": "POST, GET, OPTIONS",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  try {
    const { subject, messageBody, terminalName, restaurantName } = await req.json();

    if (!messageBody || !subject) {
      return new Response(JSON.stringify({ error: "Missing required fields (subject, messageBody)" }), {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
        status: 400,
      });
    }

    const SENDGRID_API_KEY = Deno.env.get("SENDGRID_API_KEY") || "";
    const SENDGRID_FROM_EMAIL = Deno.env.get("SENDGRID_FROM_EMAIL") || "info@spoonfulpos.com";
    const SENDGRID_FROM_NAME = Deno.env.get("SENDGRID_FROM_NAME") || "Spoonful POS Support";
    const TO_EMAIL = "info@spoonfulpos.com"; // Support destination email

    const htmlBody = `
      <div style="font-family: 'Inter', Helvetica, Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 30px; border: 1px solid #f0f0f0; border-radius: 16px; background-color: #ffffff; box-shadow: 0 4px 12px rgba(0,0,0,0.02);">
        <div style="text-align: center; margin-bottom: 24px; border-bottom: 2px solid #ef4444; padding-bottom: 12px;">
          <h2 style="color: #ef4444; font-weight: 800; font-size: 22px; margin: 0;">Spoonful POS Troubleshooting Request 🛠️</h2>
        </div>
        <p style="color: #1e293b; font-size: 15px; line-height: 1.5; margin-top: 0;">
          A support ticket has been opened from a POS device terminal.
        </p>
        <div style="background-color: #f8fafc; padding: 16px; border-radius: 12px; margin: 20px 0; border: 1px solid #e2e8f0; font-size: 14px;">
          <p style="margin: 4px 0;"><strong>Active Restaurant:</strong> ${restaurantName || 'Not Set'}</p>
          <p style="margin: 4px 0;"><strong>Terminal ID/Name:</strong> ${terminalName || 'Not Set'}</p>
          <p style="margin: 4px 0;"><strong>Subject:</strong> ${subject}</p>
        </div>
        <div style="background-color: #fef2f2; padding: 20px; border-radius: 12px; margin: 20px 0; border: 1px solid #fee2e2; color: #1f2937; line-height: 1.6; font-size: 14px; white-space: pre-wrap;">
          <strong>Message from Client:</strong><br/>
          ${messageBody}
        </div>
        <div style="border-top: 1px solid #f0f0f0; padding-top: 20px; text-align: center; color: #64748b; font-size: 11px;">
          This message was auto-generated by the Spoonful POS Android terminal diagnostics portal.
        </div>
      </div>
    `;

    if (SENDGRID_API_KEY) {
      console.log(`Sending troubleshooting request to Support via SendGrid...`);
      const response = await fetch("https://api.sendgrid.com/v3/mail/send", {
        method: "POST",
        headers: {
          "Authorization": `Bearer ${SENDGRID_API_KEY}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          personalizations: [
            {
              to: [{ email: TO_EMAIL }],
              subject: `[SUPPORT REQUEST] ${subject}`,
            },
          ],
          from: {
            email: SENDGRID_FROM_EMAIL,
            name: SENDGRID_FROM_NAME,
          },
          content: [
            {
              type: "text/html",
              value: htmlBody,
            },
          ],
        }),
      });

      if (!response.ok) {
        const errorText = await response.text();
        console.error("SendGrid API returned error:", response.status, errorText);
        throw new Error(`SendGrid API error: ${errorText}`);
      }

      console.log("Troubleshooting request email successfully dispatched via SendGrid!");
      return new Response(JSON.stringify({ success: true, message: "Email sent successfully" }), {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
        status: 200,
      });
    } else {
      console.log("SENDGRID_API_KEY not configured. Mock Email Output:\n", htmlBody);
      return new Response(JSON.stringify({ success: true, message: "SENDGRID_API_KEY not set. Mock email logged successfully." }), {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
        status: 200,
      });
    }

  } catch (error: any) {
    console.error("Troubleshoot email dispatch failed:", error);
    return new Response(JSON.stringify({ success: false, error: error.message }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
      status: 500,
    });
  }
});
